spring:
  application:
    name: admin-server
  boot:
    admin:
      context-path: /admin    # 配置访问路径为：http://localhost:8889/admin
server:
  port: 8889
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/,http://localhost:8762/eureka/