
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
spring:
  application:
    name: custom-2
#  cloud:
#    config:
#      uri: http://localhost:8888
server:
  port: 8766
feign:
  hystrix:
    enabled: true


#Unable to connect to Command Metric Stream
management:
  endpoints:
      web:
        exposure:
          include: hystrix.stream
  server:
    port: 8821
#  security:
#    enabled: false