#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

# 单server时设置为false,禁止抓去注册信息
#    fetch-registry: false
# 默认是否注册到eureka
#    register-with-eureka: false

#  server:
#  自我保护模式关闭
#    enable-self-preservation: false
#
#    eviction-interval-timer-in-ms: 5000
#server:
#  port: 8761
spring:
  profiles:
    active: server1
  application:
    name: eureka-server

info: #定义各种额外的详情给服务端显示
  app:
    name: "@project.name@" #从pom.xml中获取
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"

management:
  endpoints:
    web:
      exposure:
        include: "*"